/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.connection;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class telaCadastro extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    String nome, login, senha, dataNasc, genero;

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        initComponents();

        txtSenha.setEchoChar((char) 0);

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/branco1.jpg")).getImage());

        Calendar c = Calendar.getInstance();

        String ano = String.valueOf(c.get(Calendar.YEAR));
        String mes = String.valueOf(c.get(Calendar.MONTH));
        String dia = String.valueOf(c.get(Calendar.DAY_OF_MONTH));
        
        dataDia.setSelectedItem(dia);
        dataAno.setSelectedItem(ano);
        dataMes.setSelectedItem(mes);

        genPerso.setVisible(false);
        txtNom.setFont(new Font("Dialog", Font.ITALIC, 15));
        txtNom.setForeground(Color.gray);
        txtSn.setFont(new Font("Dialog", Font.ITALIC, 15));
        txtSn.setForeground(Color.gray);
        txtCont.setFont(new Font("Dialog", Font.ITALIC, 15));
        txtCont.setForeground(Color.gray);
        txtSenha.setFont(new Font("Dialog", Font.ITALIC, 15));
        txtSenha.setForeground(Color.gray);
        genPerso.setFont(new Font("Dialog", Font.ITALIC, 15));
        genPerso.setForeground(Color.gray);

        conexao = connection.conector();
    }

    public void Cadastro() {

        try {
            Connection conexao = new connection().conector();

            String sql = "insert into tb_user(nome, login, senha, dataNasc, genero) values('" + nome + "','" + login + "','" + senha + "','" + dataNasc + "','" + genero + "');";

            PreparedStatement statement = conexao.prepareStatement(sql);
            statement.execute();

            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cadastrado inválido.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dia = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        ano = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        masc = new javax.swing.JRadioButton();
        JComboBox = new javax.swing.JRadioButton();
        fem = new javax.swing.JRadioButton();
        pers = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        painel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNom = new javax.swing.JTextField();
        txtSn = new javax.swing.JTextField();
        txtCont = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dataDia = new javax.swing.JComboBox<>();
        dataMes = new javax.swing.JComboBox<>();
        dataAno = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        genMasc = new javax.swing.JRadioButton();
        perso = new javax.swing.JRadioButton();
        genFem = new javax.swing.JRadioButton();
        genPerso = new javax.swing.JTextField();
        btnCad = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(219, 219, 219)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtNome.setText("Nome");
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 185, 44));

        txtSobrenome.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtSobrenome.setText("Sobrenome");
        jPanel1.add(txtSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, 44));

        txtContato.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtContato.setText("Celular ou email");
        jPanel1.add(txtContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 44));

        txtPass.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtPass.setText("Nova senha");
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 370, 44));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gênero");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 60, 60));

        dia.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dia.setSelectedIndex(14);
        jPanel1.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 44));

        mes.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));
        mes.setSelectedIndex(8);
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, 44));

        ano.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        ano.setSelectedIndex(117);
        jPanel1.add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 44));

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Data de nascimento");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 60));

        masc.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        masc.setText("Masculino");
        jPanel1.add(masc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, 40));

        JComboBox.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        JComboBox.setText("Personalizado");
        jPanel1.add(JComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 140, 40));

        fem.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fem.setText("Feminino");
        jPanel1.add(fem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 40));

        pers.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        pers.setText("Gênero");
        jPanel1.add(pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 370, 44));

        btnCadastrar.setBackground(new java.awt.Color(51, 153, 0));
        btnCadastrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastre-se");
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 200, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel2.setBackground(new java.awt.Color(255, 255, 255));
        painel2.setForeground(new java.awt.Color(255, 255, 255));
        painel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastre-se");
        painel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("É rápido e fácil.");
        painel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cadastre-se");
        painel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("É rápido e fácil.");
        painel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(219, 219, 219)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNom.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtNom.setText("Nome");
        txtNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomFocusLost(evt);
            }
        });
        jPanel2.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 185, 44));

        txtSn.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtSn.setText("Sobrenome");
        txtSn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSnFocusLost(evt);
            }
        });
        jPanel2.add(txtSn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 180, 44));

        txtCont.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtCont.setText("Celular ou email");
        txtCont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContFocusLost(evt);
            }
        });
        jPanel2.add(txtCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 44));

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gênero");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 60, 60));

        dataDia.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        dataDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dataDia.setSelectedIndex(14);
        jPanel2.add(dataDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 44));

        dataMes.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        dataMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));
        dataMes.setSelectedIndex(8);
        jPanel2.add(dataMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 120, 44));

        dataAno.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        dataAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        dataAno.setSelectedIndex(117);
        jPanel2.add(dataAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 120, 44));

        jLabel8.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Data de nascimento");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, 80));

        genMasc.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        genMasc.setText("Masculino");
        genMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genMascActionPerformed(evt);
            }
        });
        jPanel2.add(genMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 110, 40));

        perso.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        perso.setText("Personalizado");
        perso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persoActionPerformed(evt);
            }
        });
        jPanel2.add(perso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 140, 40));

        genFem.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        genFem.setText("Feminino");
        genFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFemActionPerformed(evt);
            }
        });
        jPanel2.add(genFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 40));

        genPerso.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        genPerso.setText("Gênero");
        genPerso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                genPersoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                genPersoFocusLost(evt);
            }
        });
        genPerso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genPersoMouseClicked(evt);
            }
        });
        jPanel2.add(genPerso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 370, 44));

        btnCad.setBackground(new java.awt.Color(51, 153, 0));
        btnCad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCad.setForeground(new java.awt.Color(255, 255, 255));
        btnCad.setText("Cadastre-se");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        jPanel2.add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 200, 40));

        txtSenha.setFont(new java.awt.Font("Dialog", 2, 15)); // NOI18N
        txtSenha.setText("Senha");
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 370, 40));

        painel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 390));

        getContentPane().add(painel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 460));

        setSize(new java.awt.Dimension(403, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void persoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persoActionPerformed

        genFem.setSelected(false);
        genMasc.setSelected(false);
        genPerso.setVisible(true);
    }//GEN-LAST:event_persoActionPerformed

    private void genMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genMascActionPerformed

        perso.setSelected(false);
        genFem.setSelected(false);
        genPerso.setVisible(false);
    }//GEN-LAST:event_genMascActionPerformed

    private void genFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFemActionPerformed

        perso.setSelected(false);
        genMasc.setSelected(false);
        genPerso.setVisible(false);
    }//GEN-LAST:event_genFemActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed

    }//GEN-LAST:event_txtSenhaActionPerformed

    private void genPersoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genPersoMouseClicked

        if (genPerso.getText().equals("Gênero")) {
            genPerso.setText("");
        }
    }//GEN-LAST:event_genPersoMouseClicked

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed

        nome = txtNom.getText() + " " + txtSn.getText();
        login = txtCont.getText();
        senha = txtSenha.getText();
        dataNasc = dataDia.getSelectedItem().toString() + "/" + dataMes.getSelectedItem().toString() + "/" + dataAno.getSelectedItem().toString();
        genero = "masc";
        if (genFem.isSelected()) {

            genero = genFem.getText();
        }
        if (genMasc.isSelected()) {

            genero = genMasc.getText();
        }
        if (perso.isSelected()) {

            genero = genPerso.getText();
        }

        Cadastro();
    }//GEN-LAST:event_btnCadActionPerformed

    private void txtNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusGained

        if (txtNom.getText().equals("Nome")) {

            txtNom.setText("");
            txtNom.setFont(new Font("Dialog", Font.PLAIN, 15));
            txtNom.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNomFocusGained

    private void txtNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusLost

        if (txtNom.getText().equals("")) {

            txtNom.setText("Nome");
            txtNom.setFont(new Font("Dialog", Font.ITALIC, 15));
            txtNom.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNomFocusLost

    private void txtSnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSnFocusGained

        if (txtSn.getText().equals("Sobrenome")) {

            txtSn.setText("");
            txtSn.setFont(new Font("Dialog", Font.PLAIN, 15));
            txtSn.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSnFocusGained

    private void txtSnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSnFocusLost

        if (txtSn.getText().equals("")) {

            txtSn.setText("Sobrenome");
            txtSn.setFont(new Font("Dialog", Font.ITALIC, 15));
            txtSn.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSnFocusLost

    private void txtContFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContFocusGained

        if (txtCont.getText().equals("Celular ou email")) {

            txtCont.setText("");
            txtCont.setFont(new Font("Dialog", Font.PLAIN, 15));
            txtCont.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtContFocusGained

    private void txtContFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContFocusLost

        if (txtCont.getText().equals("")) {

            txtCont.setText("Celular ou email");
            txtCont.setFont(new Font("Dialog", Font.ITALIC, 15));
            txtCont.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtContFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained

        if (txtSenha.getText().equals("Senha")) {

            txtSenha.setText("");
            txtSenha.setEchoChar('*');
            txtSenha.setFont(new Font("Dialog", Font.PLAIN, 15));
            txtSenha.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost

        if (txtSenha.getText().equals("")) {

            txtSenha.setEchoChar((char) 0);
            txtSenha.setText("Senha");
            txtSenha.setFont(new Font("Dialog", Font.ITALIC, 15));
            txtSenha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void genPersoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genPersoFocusGained
        
        if (genPerso.getText().equals("Gênero")) {

            genPerso.setText("");
            genPerso.setFont(new Font("Dialog", Font.PLAIN, 15));
            genPerso.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_genPersoFocusGained

    private void genPersoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genPersoFocusLost
        
        if (genPerso.getText().equals("")) {
            
            genPerso.setText("Gênero");
            genPerso.setFont(new Font("Dialog", Font.ITALIC, 15));
            genPerso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_genPersoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JComboBox;
    private javax.swing.JComboBox<String> ano;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> dataAno;
    private javax.swing.JComboBox<String> dataDia;
    private javax.swing.JComboBox<String> dataMes;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JRadioButton fem;
    private javax.swing.JRadioButton genFem;
    private javax.swing.JRadioButton genMasc;
    private javax.swing.JTextField genPerso;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton masc;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JPanel painel2;
    private javax.swing.JTextField pers;
    private javax.swing.JRadioButton perso;
    private javax.swing.JTextField txtCont;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPass;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSn;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
